=== GaunaRocioAnahi/RepostorioDeApuntes/Lenguaje de Marcas/Relacion5/ejerciccio8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="redSocial">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="usuario" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombreUsuario">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Za-z0-9_]{3,15}" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="email">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern
                                                        value="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="seguidores">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger" />
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="publicacion" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo" type="xs:string" />
                                                    <xs:element name="fecha" type="xs:date" />
                                                    <xs:element name="like">
                                                        <xs:simpleType>
                                                            <xs:restriction
                                                                base="xs:positiveInteger" />
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="comentario">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="autor"></xs:element>
                                                                <xs:element name="contenido"></xs:element>
                                                                <xs:element name="fecha"
                                                                    type="xs:date" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name=" id" type="xs:positiveInteger" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GaunaRocioAnahi/RepostorioDeApuntes/Lenguaje de Marcas/UD1/Relacion5/ejercicio8.xml
<?xml version="1.0" encoding="UTF-8"?>
<redSocial xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejerciccio8.xsd">
    <usuarios>
        <usuario id="12">
            <nombreUsuario>pepita10_10</nombreUsuario>
            <email>pepita@hotmail.com</email>
            <seguidores>123</seguidores>
            <publicacion>
                <titulo>lo mejor</titulo>
                <fecha>2025-12-30</fecha>
                <like>123</like>
                <comentario>
                    <autor>esteban</autor>
                    <contenido>humor</contenido>
                    <fecha>2025-11-28</fecha>
                </comentario>
            </publicacion>
        </usuario>
    </usuarios>
</redSocial>
