<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curso [
    <!ELEMENT curso (nombre,alumno+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT alumno (nombre, apellido)>
    <!ELEMENT apellido (#PCDATA)>
]>
<curso>
    <nombre>programacion</nombre>
    <alumno>
        <nombre>emanuel</nombre>
        <apellido>vivas</apellido>
    </alumno>
    <alumno>
        <nombre>fermin</nombre>
        <apellido>perez</apellido>
    </alumno>
</curso>