<!DOCTYPE equipo [
    <!ELEMENT equipo (nombre, tipo, nivel)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT nivel (#PCDATA)>
]>
<equipo>
<pokemon>
    <nombre> snorlax</nombre>
    <tipo> Normal</tipo>
    <nivel>No evoluciona </nivel>
</pokemon>
</equipo>
