=== GaunaRocioAnahi/RepostorioDeApuntes/Lenguaje de Marcas/UD1/Relacion5/ejercicio9.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hospital">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" />
                <xs:element name="departamentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departamento" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Urgencias" />
                                                    <xs:enumeration value="Pediatria" />
                                                    <xs:enumeration value="Traumatologia" />
                                                    <xs:enumeration value="Oncologia" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="medicoJefe">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z].*" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="pacientes">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="paciente" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="dni">
                                                                    <xs:simpleType>
                                                                        <xs:restriction
                                                                            base="xs:string">
                                                                            <xs:pattern
                                                                                value="\d{8}[A-Za-z]" />
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="edad">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:integer">
                                                                            <xs:minInclusive value="0"/>
                                                                            <xs:maxInclusive value="120"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                                <xs:element name="fechaIngreso" type="xs:date"/>
                                                                <xs:element name="diagnostico" type="xs:string"/>
                                                                <xs:element name="tratamiento" type="xs:string" minOccurs="0" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GaunaRocioAnahi/RepostorioDeApuntes/Lenguaje de Marcas/Relacion5/ejercicio9.xml
<?xml version="1.0" encoding="UTF-8"?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio9.xsd">
    <nombre></nombre>
<departamentos>
        <departamento>
            <nombre></nombre>
            <medicoJefe></medicoJefe>
            <pacientes>
                <paciente>
                    <dni></dni>
                    <edad></edad>
                    <fechaIngreso></fechaIngreso>
                    <diagnostico></diagnostico>
                    <tratamiento></tratamiento>
                </paciente>
                <paciente>
                    <dni></dni>
                    <edad></edad>
                    <fechaIngreso></fechaIngreso>
                    <diagnostico></diagnostico>
                    <tratamiento></tratamiento>
                </paciente>
            </pacientes>
        </departamento>
        <departamento>
            <nombre></nombre>
            <medicoJefe></medicoJefe>
            <pacientes>
                <paciente>
                    <dni></dni>
                    <edad></edad>
                    <fechaIngreso></fechaIngreso>
                    <diagnostico></diagnostico>
                    <tratamiento></tratamiento>
                </paciente>
                <paciente>
                    <dni></dni>
                    <edad></edad>
                    <fechaIngreso></fechaIngreso>
                    <diagnostico></diagnostico>
                    <tratamiento></tratamiento>
                </paciente>
            </pacientes>
        </departamento>
    </departamentos>

</hospital>

=== GaunaRocioAnahi/RepostorioDeApuntes/Lenguaje de Marcas/UD1/Relacion5/ejercicio9.xml
<?xml version="1.0" encoding="UTF-8"?>
<hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio9.xsd">
    <nombre>ÃŒtaliano</nombre>
<departamentos>
        <departamento>
            <nombre>Urgencias</nombre>
            <medicoJefe>Diego Iraola</medicoJefe>
            <pacientes>
                <paciente>
                    <dni>12345678l</dni>
                    <edad>18</edad>
                    <fechaIngreso>2025-04-09</fechaIngreso>
                    <diagnostico>reservado</diagnostico>
                    <tratamiento>critico</tratamiento>
                </paciente>
                <paciente>
                    <dni>32165487m</dni>
                    <edad>17</edad>
                    <fechaIngreso>2026-06-23</fechaIngreso>
                    <diagnostico>malo</diagnostico>
                    <tratamiento>efectivo</tratamiento>
                </paciente>
            </pacientes>
        </departamento>
        <departamento>
            <nombre>Urgencias</nombre>
            <medicoJefe>Fernando Hernandez</medicoJefe>
            <pacientes>
                <paciente>
                    <dni>78456123m</dni>
                    <edad>30</edad>
                    <fechaIngreso>2025-03-03</fechaIngreso>
                    <diagnostico>critico</diagnostico>
                    <tratamiento>bien</tratamiento>
                </paciente>
                <paciente>
                    <dni>13211126l</dni>
                    <edad>40</edad>
                    <fechaIngreso>2520-12-21</fechaIngreso>
                    <diagnostico>reservado</diagnostico>
                    <tratamiento>transplante</tratamiento>
                </paciente>
            </pacientes>
        </departamento>
    </departamentos>

</hospital>
